theme: minima
minima:
  skin: solarized-light
gems:
  - jekyll-layouts
title: Moins c'est mieux
author:
  name: Sandrine et Jérôme
  email: mcm@gmail.com
description: >
  Projet de couple vers une vie plus proche de nos aspirations !
header_pages:
  - projet.md
  - autonomie.md
  - lieu.md
  - aide.md
